#!/usr/bin/env -S npx tsx

// ./src/constants/typography/script.ts
import fs from "node:fs"
import path from "node:path"
import postcss from "postcss"
import { VARIANT_SIZING } from "./sizing"
import { TRACKING } from "./tracking"

const kebabCaseUtil = (str: string) =>
  str.replace(/([a-z])(?=[A-Z\d])/g, "$1-").toLowerCase()

const pleaseDoNotEdit = postcss.comment({
  text: "Please do not edit this file.",
})

const css = postcss.root({
  nodes: [pleaseDoNotEdit],
})

const theme = postcss.atRule({ name: "theme" })

for (const [variant, sizing] of Object.entries(VARIANT_SIZING)) {
  const casedVariant = kebabCaseUtil(variant)
  const normalSizing = sizing.lg
  const tracking = TRACKING[sizing.sm.size]

  theme.append({
    prop: `--text-${casedVariant}`,
    value: `${normalSizing.size}px`,
  })
  theme.append({
    prop: `--text-${casedVariant}--line-height`,
    value: `${normalSizing.leading}px `,
  })
  theme.append({
    prop: `--text-${casedVariant}--letter-spacing`,
    value: `${tracking}px`,
  })
}

css.append(theme)

const cssPath = path.join(import.meta.dirname, "typography.css")

fs.writeFileSync(cssPath, css.toString())
