#!/usr/bin/env -S npx tsx

// ./src/constants/typography/script.ts
import fs from "node:fs"
import path from "node:path"
import postcss from "postcss"
import { VARIANT_SIZING } from "./sizing"
import { TRACKING } from "./tracking"
import type { TBreakpoint, TVariant } from "~/constants/typography/types"

const kebabCaseUtil = (str: string) =>
  str.replace(/([a-z])(?=[A-Z\d])/g, "$1-").toLowerCase()

const appendTextVariables = (
  node: postcss.Container,
  variant: string,
  fontSize: number,
  lineHeight: number,
  letterSpacing: number,
) => {
  node.append({
    prop: `--text-${variant}`,
    value: `${fontSize}px`,
  })
  node.append({
    prop: `--text-${variant}--line-height`,
    value: `${lineHeight}px `,
  })
  node.append({
    prop: `--text-${variant}--letter-spacing`,
    value: `${letterSpacing}px`,
  })
}

const pleaseDoNotEdit = postcss.comment({
  text: "Please do not edit this file.",
})

const cssRoot = postcss.root({
  nodes: [pleaseDoNotEdit],
})

const atThemeRule = postcss.atRule({ name: "theme" })

for (const variant in VARIANT_SIZING) {
  const casedVariant = kebabCaseUtil(variant)
  const breakpointSizing = VARIANT_SIZING[variant as TVariant]

  for (const breakpoint in breakpointSizing) {
    const sizing = breakpointSizing[breakpoint as TBreakpoint]
    const fontSize = sizing.size
    const lineHeight = sizing.leading
    const letterSpacing = TRACKING[fontSize]

    if (breakpoint === "sm") {
      appendTextVariables(
        atThemeRule,
        casedVariant,
        fontSize,
        lineHeight,
        letterSpacing,
      )
    } else {
      const atMediaRule = postcss.atRule({
        name: "media",
        params: `(width >= theme(--breakpoint-${breakpoint}))`,
      })
      const rootRule = postcss.rule({
        selector: ":root",
      })

      appendTextVariables(
        rootRule,
        casedVariant,
        fontSize,
        lineHeight,
        letterSpacing,
      )

      atMediaRule.append(rootRule)
      cssRoot.append(atMediaRule)
    }
  }
}

cssRoot.append(atThemeRule)

const cssPath = path.join(import.meta.dirname, "typography.css")

fs.writeFileSync(cssPath, cssRoot.toString())
