#!/usr/bin/env -S npx tsx

import fs from "node:fs"
import path from "node:path"
import postcss from "postcss"
import { VARIANT_SIZING } from "./sizing"
import { TRACKING } from "./tracking"
import type { TVariant } from "~/constants/typography/types"

const css = postcss.root({
  nodes: [
    postcss.comment({
      text: "Please do not edit this file.",
    }),
  ],
})

const theme = postcss.atRule({
  name: "theme",
})

for (const variant in VARIANT_SIZING) {
  const casedVariant = variant
    .replace(/([a-z])(?=[A-Z\d])/g, "$1-")
    .toLowerCase()

  const { size: fontSize, leading: lineHeight } =
    VARIANT_SIZING[variant as TVariant]

  const letterSpacing = TRACKING[fontSize]

  theme.append({
    prop: `--text-${casedVariant}`,
    value: `${fontSize / 16}rem`,
  })
  theme.append({
    prop: `--text-${casedVariant}--line-height`,
    value: `${lineHeight / 16}rem`,
  })
  theme.append({
    prop: `--text-${casedVariant}--letter-spacing`,
    value: `${letterSpacing / 1000}em`,
  })
}

css.append(theme)

const cssPath = path.join(import.meta.dirname, "typography.css")

fs.writeFileSync(cssPath, css.toString())
